apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ashreesee/frontend
    argocd-image-updater.argoproj.io/ashreesee_frontend.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/Ashreesee/argo-apps-repo.git
    targetRevision: main
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
