apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kargo
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ashreesee/frontend
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend  # Fixed indentation
          image: ashreesee/frontend:76800cf-20250417082924
          ports:
            - containerPort: 5000  # Fixed indentation
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:3000/"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"