apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend  # Fixed indentation
          image: ashreesee/frontend:latest
          ports:
            - containerPort: 5000  # Fixed indentation
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:3000/"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"