apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-stage
  namespace: kargo
spec:
  warehouse: frontend
  subscriptions:
    - warehouse: frontend
  promotionMechanisms:
    argoCDAppUpdates:
      - appRef:
          name: frontend-app
        imageUpdate:
          - container: frontend
            imageRepo: ghcr.io/ashreesee/frontend
