apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-stage
  namespace: kargo
spec:
  subscriptions:
    warehouse: backend-warehouse
  promotionMechanisms:
    gitRepoUpdate:
      repoURL: https://github.com/ashreesee/argo-apps-repo.git
      writeBranch: main
      kustomize:
        path: backend
